#!/usr/bin/env python

import sys
import argparse
import requests

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--url', required=True, help='url of the json api')
    parser.add_argument('--key', required=True, help='key to look for in json')
    parser.add_argument('--ok-value', required=True, help='ok value the key should have in json')
    parser.add_argument('--warning-value', help='warning value the key should have in json')
    parser.add_argument('--error-value', help='error value the key should have in json')
    parser.add_argument('--description', help='print the full json return value with the status message')

    args = parser.parse_args()

    url = args.url
    key = args.key
    ok_value = args.ok_value
    error_value = args.error_value
    warning_value = args.error_value
    verbose = args.description

    description = ''

    try:
        r = requests.get(url)
        if verbose:
            description = '| ' + r.text
        data_list = r.json()
    except:
        print "UNKNOWN: URL '%s' could not be reached or did not return json %s" % (url, description)
        sys.exit(2)

    error_found = False
    warning_found = False
    ok_found = False
    nok_found = False
    # HACK: allow other types at the root
    if type(data_list) is dict:
        data_list = [data_list]
    for data in data_list:
        if key in data:
            if error_value and str(data[key]) == str(error_value):
                error_found = True
            elif warning_value and str(data[key]) == str(warning_value):
                warning_found = True
            elif str(data[key]) == str(ok_value):
                ok_found = True
            else:
                nok_found = True

    if error_found:
        print "ERROR: Key '%s' with error-value '%s' found on %s %s" % (key, error_value, url, description)
        sys.exit(2)
    elif warning_found:
        print "ERROR: Key '%s' with warning-value '%s' found on %s %s" % (key, warning_value, url, description)
        sys.exit(1)
    elif ok_found:
        print "OK: Key '%s' with ok-value '%s' found on %s %s" % (key, ok_value, url, description)
    elif nok_found:
        print "ERROR: Key '%s' is not ok on %s %s" %  (key, url, description)
        sys.exit(2)
    else:
        print "UNKNOWN: Key '%s' not found or ok_value '%s' or error_value '%s' not found on %s %s" % (key, ok_value, error_value, url, description)
        sys.exit(3)

if __name__ == "__main__":
    main()

